/*
*   minesweeper.h
*
*   MediOS project
*   Copyright (c) 2005 by Christophe THOMAS (oxygen77 at free.fr)
*
* All files in this archive are subject to the GNU General Public License.
* See the file COPYING in the source tree root for full license agreement.
* This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
* KIND, either express of implied.
*
* initial code from Schoki - Linav project 2004
* 
*
*/

#ifndef __APPS_MINESWEEPER
#define __APPS_MINESWEEPER

/* config struct */
struct minesweeper_s {
    /* action definition*/
    int action_exit;
    int action_newgame;
    int action_left;
    int action_right;
    int action_up;
    int action_down;
    int action_toggleflag;
    int action_discover;
    int action_settings;
};

/* default config */
struct minesweeper_s default_conf = {
    BTN_OFF,BTN_ON,
    BTN_LEFT,BTN_RIGHT,BTN_UP,BTN_DOWN,
    BTN_F1,BTN_F2,BTN_F3
};

/* Av4 config */
struct minesweeper_s av4_conf = {
    BTN_F2,BTN_F1,
    BTN_LEFT,BTN_RIGHT,BTN_UP,BTN_DOWN,
    BTN_OFF,BTN_ON,BTN_F3
};

/* config table */

struct minesweeper_entry {
    int arch;
    struct minesweeper_s * conf;
};

struct minesweeper_entry conf_tab[] = {
    {AV3XX_ARCH,    &default_conf},
    {GMINI4XX_ARCH, &default_conf},
    {AV1XX_ARCH,    &default_conf},
    {JBMM_ARCH,     &default_conf},
    {GMINI402_ARCH, &default_conf},
    {AV4XX_ARCH,    &av4_conf},
    {PMA_ARCH,      &default_conf},
    {AV5XX_ARCH,    &default_conf},
    {-1,            NULL}
};

/* the tile struct
if there is a mine, mine is true
if tile is known by player, known is true
if tile has a flag, flag is true
neighbors is the total number of mines arround tile
*/
typedef struct tile_s {
    unsigned char mine : 1;
    unsigned char known : 1;
    unsigned char flag : 1;
    unsigned char neighbors : 4;
} tile;

/* function header */
void init_field(void);
void displayMineField(void);

/* bitmap of the game */

#define PIECE_DIM 12

static unsigned char emptyField[PIECE_DIM][PIECE_DIM] =
{ { BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR} };

static unsigned char oneField[PIECE_DIM][PIECE_DIM] =
{ { BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_ONE_COLOR,  TXT_ONE_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_ONE_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_ONE_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_ONE_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_ONE_COLOR,  TXT_ONE_COLOR,  TXT_ONE_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR} };

static unsigned char twoField[PIECE_DIM][PIECE_DIM] =
{ { BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_TWO_COLOR,  TXT_TWO_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_TWO_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_TWO_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_TWO_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_TWO_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_TWO_COLOR,  TXT_TWO_COLOR,  TXT_TWO_COLOR,  TXT_TWO_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR} };

static unsigned char threeField[PIECE_DIM][PIECE_DIM] =
{ { BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_THREE_COLOR,  TXT_THREE_COLOR,  TXT_THREE_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_THREE_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_THREE_COLOR,  TXT_THREE_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_THREE_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_THREE_COLOR,  TXT_THREE_COLOR,  TXT_THREE_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR} };

static unsigned char fourField[PIECE_DIM][PIECE_DIM] =
{ { BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_FOUR_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_FOUR_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_FOUR_COLOR,  TXT_FOUR_COLOR,  TXT_FOUR_COLOR,  TXT_FOUR_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_FOUR_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_FOUR_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR} };

static unsigned char fiveField[PIECE_DIM][PIECE_DIM] =
{ { BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_FIVE_COLOR,  TXT_FIVE_COLOR,  TXT_FIVE_COLOR,  TXT_FIVE_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_FIVE_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_FIVE_COLOR,  TXT_FIVE_COLOR,  TXT_FIVE_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_FIVE_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_FIVE_COLOR,  TXT_FIVE_COLOR,  TXT_FIVE_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR} };

static unsigned char sixField[PIECE_DIM][PIECE_DIM] =
{ { BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_SIX_COLOR,  TXT_SIX_COLOR,  TXT_SIX_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_SIX_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_SIX_COLOR,  TXT_SIX_COLOR,  TXT_SIX_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_SIX_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_SIX_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_SIX_COLOR,  TXT_SIX_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR} };

static unsigned char sevenField[PIECE_DIM][PIECE_DIM] =
{ { BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_SEVEN_COLOR,  TXT_SEVEN_COLOR,  TXT_SEVEN_COLOR,  TXT_SEVEN_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_SEVEN_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_SEVEN_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_SEVEN_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_SEVEN_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR} };

static unsigned char eightField[PIECE_DIM][PIECE_DIM] =
{ { BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_EIGHT_COLOR,  TXT_EIGHT_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_EIGHT_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_EIGHT_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_EIGHT_COLOR,  TXT_EIGHT_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  TXT_EIGHT_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_EIGHT_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  TXT_EIGHT_COLOR,  TXT_EIGHT_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  FIELD_FOUND_COLOR,  BG_COLOR},
{ BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR} };

static BITMAP num_bitmap[] = {
    {(unsigned int) emptyField, PIECE_DIM, PIECE_DIM, 0, 0},
    {(unsigned int) oneField,   PIECE_DIM, PIECE_DIM, 0, 0},
    {(unsigned int) twoField,   PIECE_DIM, PIECE_DIM, 0, 0},
    {(unsigned int) threeField, PIECE_DIM, PIECE_DIM, 0, 0},
    {(unsigned int) fourField,  PIECE_DIM, PIECE_DIM, 0, 0},
    {(unsigned int) fiveField,  PIECE_DIM, PIECE_DIM, 0, 0},
    {(unsigned int) sixField,   PIECE_DIM, PIECE_DIM, 0, 0},
    {(unsigned int) sevenField, PIECE_DIM, PIECE_DIM, 0, 0},
    {(unsigned int) eightField, PIECE_DIM, PIECE_DIM, 0, 0}
};

unsigned char Flag_data[12][12] = {
{ BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR},
{BG_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,0x0c,0x0c,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,BG_COLOR},
{BG_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,0x0c,0x0c,0x0c,0x0c,0x03,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,BG_COLOR},
{BG_COLOR,0x0c,0x0c,0x0c,0x0c,0x0c,0x0c,0x03,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,BG_COLOR},
{BG_COLOR,0x0c,0x0c,0x0c,0x0c,0x0c,0x0c,0x03,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,BG_COLOR},
{BG_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,0x0c,0x0c,0x0c,0x0c,0x03,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,BG_COLOR},
{BG_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,0x03,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,BG_COLOR},
{BG_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,0x03,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,BG_COLOR},
{BG_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,0x07,0x07,0x03,0x07,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,BG_COLOR},
{BG_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,0x07,0x07,0x08,0x08,0x03,0x08,0x07,FIELD_FOUND_COLOR,BG_COLOR},
{BG_COLOR,FIELD_FOUND_COLOR,0x08,0x08,0x08,0x08,0x08,0x08,0x08,0x08,0x08,BG_COLOR},
{ BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR}};

	static unsigned char Mine_data[PIECE_DIM][PIECE_DIM] = {
{ BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR},
{BG_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,COLOR_BLACK,COLOR_BLACK,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,BG_COLOR},
{BG_COLOR,FIELD_FOUND_COLOR,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,FIELD_FOUND_COLOR,BG_COLOR},
{BG_COLOR,FIELD_FOUND_COLOR,COLOR_BLACK,COLOR_LIGHT_GREY,COLOR_LIGHT_GREY,COLOR_LIGHT_GREY,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,FIELD_FOUND_COLOR,BG_COLOR},
{BG_COLOR,COLOR_BLACK,COLOR_BLACK,COLOR_LIGHT_GREY,COLOR_LIGHT_GREY,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,BG_COLOR},
{BG_COLOR,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,BG_COLOR},
{BG_COLOR,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,BG_COLOR},
{BG_COLOR,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,BG_COLOR},
{BG_COLOR,FIELD_FOUND_COLOR,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,FIELD_FOUND_COLOR,BG_COLOR},
{BG_COLOR,FIELD_FOUND_COLOR,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,COLOR_BLACK,FIELD_FOUND_COLOR,BG_COLOR},
{BG_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,COLOR_BLACK,COLOR_BLACK,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,FIELD_FOUND_COLOR,BG_COLOR},
{ BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR,  BG_COLOR}};

static BITMAP Flag_bitmap = {(unsigned int) Flag_data, PIECE_DIM, PIECE_DIM, 0, 0};
static BITMAP Mine_bitmap = {(unsigned int) Mine_data, PIECE_DIM, PIECE_DIM, 0, 0};

#endif
