#!/bin/sh
# create files

rm -f tmp.lng

awk 'BEGIN{FS="[\t ]*#[\t ]*"; numID=0;} \
NF==0{next} \
{printf "%c%c%s\0",numID/0x100,numID%0x100,$2;numID++}' $1 > tmp.lng

./script/mkLng tmp.lng $2 $3

rm -f tmp.lng
