include ../../../Makefile.conf

ASFLAGS  += -I../../../include -I../../../medios/include -I. -I../
GCCFLAGS += -I../../../include -I../../../medios/include -I. -I../ -O3

BUILD_DIR = ../build
all: do_build

include ../../../default.rule