#!/bin/sh

which svn &> /dev/null
if [ $? -eq 0 ]
then
svn info &> /dev/null
if [ $? -eq 0 ]
then
echo -n "#define VERSION_NUMBER \"" > tmp.h
svn info |grep Revision | awk -F " " '{print "\"" $2 "\""}' >> tmp.h
echo "\"" >> tmp.h
else
echo "//No SVN Version" > tmp.h
echo "" >> tmp.h
fi
else
echo "//No SVN Version" > tmp.h
echo "" >> tmp.h
fi
exit
if [ -f $1 ]
then
    cmp -s $1 tmp.h

    if [ $? -eq 1 ]
    then
        mv tmp.h $1
    else
        rm tmp.h
    fi
else
    mv tmp.h $1
fi
